### ISSUE TITLE
Attester controller shouldn't update spec

### ISSUE THREAD

**Issue by cplee** [liatrio/rode#20]
Whenever an attester CR is created without a secret, and the secret is then created by rode, the controller currently updates the spec of the CR setting the secret name.  This should be replaced with a status value that contains the name of the secret that is being used to avoid mutating the spec provided in the original resource.

**Comment by gesparza3** [comment]
This issue was resolved by making `pgbSecret` a required field when creating Attester resources. See [PR #29](https://github.com/liatrio/rode/pull/29)
